### ISSUE TITLE
Socket Error

### ISSUE THREAD

**Issue by Muthuramane** [intracom-telecom-sdn/oftraf#9]
I am getting the following error when I run the application and debugging on it.

Traceback (most recent call last):
  File "oftraf.py", line 459, in <module>
    bottle.run(host=args.rest_host, port=args.rest_port, quiet=True)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3117, in run
    server.run(app)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "oftraf.py", line 167, in of_sniff
    for _, pkt in pcap.pcap(name=ifname, immediate=False):
AttributeError: 'module' object has no attribute 'pcap'

  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 2771, in run
    srv = make_server(self.host, self.port, app, server_cls, handler_cls)
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 144, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in **init**
    self.server_bind()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 48, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

**Comment by anastop** [comment]
Could you provide the full command line that you use for oftraf?
